sudo: required
services:
  - docker

before_install:
  - docker build -t vernseaw/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true vernseaw/docker-react-example npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-example"
  env: "DockerReactExample-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-779455087451"
  bucket_path: "docker-react-example"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
