sudo: required
services:
  - docker

before_install:
  - docker build -t vernseaw/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true vernseaw/docker-react-example npm run test -- --coverage
